# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [19]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [20]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [21]:
sinasc_mun = sinasc_raw[['munResNome', 'IDADEMAE', 'IDADEPAI']]
sinasc_res = sinasc_mun.dropna().groupby('munResNome').mean()
sinasc_res

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.892857  29.548701
Alto Alegre dos Parecis    24.679104  29.179104
Alto Paraíso               22.833333  28.833333
Alvorada D'Oeste           26.825243  30.757282
Ariquemes                  28.133333  32.466667
Buritis                    24.750000  30.812500
Cabixi                     32.166667  34.333333
Cacaulândia                31.000000  36.333333
Cacoal                     26.978605  30.931854
Campo Novo de Rondônia     24.900000  30.500000
Candeias do Jamari         23.684211  29.894737
Castanheiras               28.071429  30.392857
Cerejeiras                 28.361111  31.652778
Chupinguaia                26.888889  29.629630
Colorado do Oeste          31.161290  34.354839
Corumbiara                 29.000000  32.470588
Costa Marques              25.250000  30.613636
Cujubim                    27.400000  31.400000
Espigão D'Oeste            26.808176  31.198113
Governador Jorge Teixeira  25.555556  29.222222
Guajará-Mirim              26.058824  30.470588
Itapuã do Oeste            31.375000  42.500000
Jaru                       28.450704  32.197183
Ji-Paraná                  27.282819  31.132239
Machadinho D'Oeste         26.048077  31.326923
Ministro Andreazza         27.890411  33.849315
Mirante da Serra           26.928571  32.154762
Monte Negro                27.642857  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   27.104167  30.520833
Nova Mamoré                26.051282  31.692308
Nova União                 27.371429  31.371429
Novo Horizonte do Oeste    26.988235  31.588235
Ouro Preto do Oeste        27.109920  31.233244
Parecis                    26.973684  32.473684
Pimenta Bueno              25.449807  29.745174
Pimenteiras do Oeste       32.600000  35.600000
Porto Velho                28.355655  32.352679
Presidente Médici          26.170854  30.150754
Primavera de Rondônia      28.083333  31.888889
Rio Crespo                 26.000000  28.000000
Rolim de Moura             26.549701  30.360479
Santa Luzia D'Oeste        26.043956  30.703297
Seringueiras               25.058824  30.500000
São Felipe D'Oeste         26.979167  31.395833
São Francisco do Guaporé   26.944444  31.638889
São Miguel do Guaporé      27.469136  32.666667
Teixeirópolis              27.454545  31.500000
Theobroma                  24.916667  30.083333
Urupá                      27.116071  31.008929
Vale do Anari              27.133333  34.000000
Vale do Paraíso            25.604651  29.976744
Vilhena                    30.611765  34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

no exercício 2 fez certinho o cálculo, aqui também tem outa opção utilizar o .loc para separar os dados pela data de nascimento (DTNASC) e realizar o pivot table com aggfun = mean.

In [22]:
sinasc_data = sinasc_raw[['ESCMAE', 'DTNASC', 'SEXO', 'PESO']].copy()

In [23]:
sinasc_0507 = sinasc_data[sinasc_data['DTNASC']=='2019-07-05'].groupby(['ESCMAE', 'SEXO'])['PESO'].mean().to_frame()
sinasc_0507

                                  PESO
ESCMAE          SEXO
1 a 3 anos      Masculino  3050.000000
12 anos ou mais Feminino   3099.166667
                Masculino  2875.500000
4 a 7 anos      Feminino   3269.500000
                Masculino  2990.000000
8 a 11 anos     Feminino   3376.875000
                Masculino  3325.000000

In [24]:
sinasc_data.pivot_table(values = ['PESO'],
                     index = ['ESCMAE', 'SEXO'],
                     columns = sinasc_data['DTNASC']=='2019-07-05',
                     aggfunc ={'PESO':['mean']})

                                  PESO
                                  mean
DTNASC                           False        True
ESCMAE          SEXO
1 a 3 anos      Feminino   3126.363636          NaN
                Masculino  3191.852113  3050.000000
12 anos ou mais Feminino   3182.784237  3099.166667
                Masculino  3310.542954  2875.500000
4 a 7 anos      Feminino   3157.542920  3269.500000
                Masculino  3290.048387  2990.000000
8 a 11 anos     Feminino   3192.865933  3376.875000
                Masculino  3305.850302  3325.000000
Nenhuma         Feminino   2972.333333          NaN
                Masculino  3178.181818          NaN

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [25]:
sinasc_mun.munResNome.value_counts()

Porto Velho                  8437
Ji-Paraná                    2182
Ariquemes                    1729
Vilhena                      1590
Cacoal                       1374
Rolim de Moura                927
Jaru                          881
Guajará-Mirim                 781
Ouro Preto do Oeste           631
Pimenta Bueno                 616
Buritis                       583
Machadinho D'Oeste            500
Espigão D'Oeste               450
Nova Mamoré                   432
Alta Floresta D'Oeste         367
São Miguel do Guaporé         353
Candeias do Jamari            337
Presidente Médici             304
São Francisco do Guaporé      303
Nova Brasilândia D'Oeste      261
Cerejeiras                    237
Costa Marques                 233
Alto Paraíso                  226
Colorado do Oeste             214
Alvorada D'Oeste              205
Cujubim                       205
Monte Negro                   199
Urupá                         170
Seringueiras                  168
Campo Novo de Rondônia        166
Mirante da Serra              164
Chupinguaia                   162
Alto Alegre dos Parecis       154
Corumbiara                    127
Governador Jorge Teixeira     112
Itapuã do Oeste               109
Nova União                    104
Santa Luzia D'Oeste            99
Novo Horizonte do Oeste        98
Theobroma                      97
Vale do Anari                  93
Ministro Andreazza             84
Vale do Paraíso                81
Cabixi                         80
Cacaulândia                    75
Teixeirópolis                  64
São Felipe D'Oeste             54
Rio Crespo                     50
Parecis                        44
Primavera de Rondônia          43
Pimenteiras do Oeste           40
Castanheiras                   32
Município ignorado - RO         1
Name: munResNome, dtype: int64

In [26]:
sinasc_mun.pivot_table(values = ['IDADEMAE', 'IDADEPAI'],
                       index = sinasc_mun['munResNome'][sinasc_mun['munResNome'] == 'Castanheiras'],
                       aggfunc ={'IDADEMAE':['min', 'max', 'mean'], 'IDADEPAI':['min', 'max', 'mean']})

             IDADEMAE                 IDADEPAI
                  max      mean   min      max       mean   min
munResNome
Castanheiras     39.0  27.28125  17.0     43.0  30.392857  17.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [27]:
sinasc_mun2 = sinasc_raw[['DTNASC', 'QTDFILVIVO', 'IDADEPAI']].copy()

In [28]:
sinasc_mun2['DTNASC'] = pd.to_datetime(sinasc_mun2['DTNASC'])

In [29]:
sinasc_mun2.set_index('DTNASC', inplace=True)

In [30]:
sinasc_mun2.index.month

Int64Index([ 2,  2,  2,  3,  3,  3,  4,  4,  2,  3,
            ...
            10, 11, 11, 11, 11, 12, 10,  8, 12, 12],
           dtype='int64', name='DTNASC', length=27028)

In [31]:
sinasc_mun2['MES'] = sinasc_mun2.index.month

In [32]:
sinasc_mun2 = sinasc_mun2.dropna()

In [33]:
sinasc_mun2.pivot_table(values = ['QTDFILVIVO', 'IDADEPAI'],
                        index = sinasc_mun2['MES'] == 3,
                        aggfunc = {'QTDFILVIVO':['min', 'max', 'mean'], 'IDADEPAI':['min', 'max', 'mean']})

      IDADEPAI                  QTDFILVIVO
           max       mean   min        max      mean  min
MES
False     86.0  31.097767  15.0       30.0  0.914362  0.0
True      62.0  31.268505  16.0        7.0  0.934688  0.0

In [34]:
sinasc_mun2 = sinasc_raw[['munResNome', 'QTDFILVIVO', 'IDADEPAI']]
sinasc_mun2.dropna().groupby('munResNome').agg(['mean', 'max', 'min'])

                          QTDFILVIVO              IDADEPAI
                                mean   max  min       mean   max   min
munResNome
Alta Floresta D'Oeste       0.843137   7.0  0.0  29.535948  58.0  17.0
Alto Alegre dos Parecis     0.880597   5.0  0.0  29.179104  50.0  16.0
Alto Paraíso                0.666667   2.0  0.0  28.833333  49.0  21.0
Alvorada D'Oeste            1.019417   9.0  0.0  30.757282  52.0  17.0
Ariquemes                   1.538462   4.0  0.0  33.153846  51.0  20.0
Buritis                     1.000000   3.0  0.0  32.469388  49.0  19.0
Cabixi                      0.500000   2.0  0.0  34.333333  47.0  19.0
Cacaulândia                 0.666667   2.0  0.0  36.333333  50.0  28.0
Cacoal                      0.889065   7.0  0.0  30.931854  66.0  17.0
Campo Novo de Rondônia      1.260870   2.0  0.0  31.000000  40.0  21.0
Candeias do Jamari          1.187500   3.0  0.0  30.187500  41.0  22.0
Castanheiras                1.178571   6.0  0.0  30.392857  43.0  17.0
Cerejeiras                  1.422535   8.0  0.0  31.690141  52.0  19.0
Chupinguaia                 0.851852   2.0  0.0  29.629630  46.0  20.0
Colorado do Oeste           0.935484   2.0  0.0  34.354839  53.0  23.0
Corumbiara                  1.000000   3.0  0.0  32.470588  52.0  21.0
Costa Marques               1.441860  14.0  0.0  30.813953  60.0  17.0
Cujubim                     2.500000   7.0  0.0  31.400000  44.0  19.0
Espigão D'Oeste             1.314465  12.0  0.0  31.198113  86.0  16.0
Governador Jorge Teixeira   0.444444   1.0  0.0  29.222222  37.0  22.0
Guajará-Mirim               0.928571   3.0  0.0  30.214286  44.0  19.0
Itapuã do Oeste             1.875000   5.0  0.0  42.500000  73.0  25.0
Jaru                        0.750000   3.0  0.0  32.235714  62.0  19.0
Ji-Paraná                   0.859903   6.0  0.0  31.127536  63.0  15.0
Machadinho D'Oeste          0.969697   8.0  0.0  31.323232  53.0  17.0
Ministro Andreazza          1.095890   6.0  0.0  33.849315  55.0  21.0
Mirante da Serra            0.904762   3.0  0.0  32.154762  56.0  20.0
Monte Negro                 0.928571   3.0  0.0  34.678571  55.0  20.0
Município ignorado - RO     1.000000   1.0  1.0  22.000000  22.0  22.0
Nova Brasilândia D'Oeste    0.854167   4.0  0.0  30.520833  48.0  20.0
Nova Mamoré                 1.628571   5.0  0.0  31.742857  43.0  20.0
Nova União                  0.826087   3.0  0.0  31.536232  53.0  18.0
Novo Horizonte do Oeste     0.773810   4.0  0.0  31.547619  56.0  20.0
Ouro Preto do Oeste         0.783784   4.0  0.0  31.235135  60.0  17.0
Parecis                     1.342105   5.0  0.0  32.473684  61.0  18.0
Pimenta Bueno               0.869903   9.0  0.0  29.739806  70.0  16.0
Pimenteiras do Oeste        1.400000   4.0  0.0  35.600000  45.0  25.0
Porto Velho                 0.994774   7.0  0.0  32.653310  65.0  16.0
Presidente Médici           0.969849   7.0  0.0  30.150754  64.0  16.0
Primavera de Rondônia       1.166667   4.0  0.0  31.888889  44.0  21.0
Rio Crespo                  2.000000   2.0  2.0  28.000000  28.0  28.0
Rolim de Moura              0.833333   5.0  0.0  30.353717  69.0  16.0
Santa Luzia D'Oeste         1.164835  30.0  0.0  30.703297  53.0  18.0
Seringueiras                0.823529   5.0  0.0  30.500000  47.0  20.0
São Felipe D'Oeste          0.808511   5.0  0.0  31.042553  57.0  18.0
São Francisco do Guaporé    0.714286   3.0  0.0  31.628571  54.0  19.0
São Miguel do Guaporé       0.765432   4.0  0.0  32.666667  60.0  19.0
Teixeirópolis               0.818182   3.0  0.0  31.500000  67.0  20.0
Theobroma                   0.416667   2.0  0.0  30.083333  45.0  23.0
Urupá                       0.945946   5.0  0.0  31.063063  48.0  17.0
Vale do Anari               0.933333   2.0  0.0  34.000000  58.0  23.0
Vale do Paraíso             0.488372   2.0  0.0  29.976744  51.0  18.0
Vilhena                     0.721893   4.0  0.0  34.147929  60.0  18.0

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

#### Alguns dados parecem inconsistentes, um exemplo é na cidade de Santa Luzia D'Oeste, o numero maximo de filhos vivos é de 30, possivelmente houve um erro na coletas dos dados, Outro dado, a média de filhos vivos na cidade de Theobroma é 0,41, onde em comparação ao município de Cujubim essa média é de 2,5.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

In [16]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [17]:
sinasc_raw.select_dtypes(exclude=['int64','float64'])

,ESCMAE,GESTACAO,GRAVIDEZ,PARTO,DTNASC,SEXO,RACACOR,DTCADASTRO,CODANOMAL,VERSAOSIST,DTRECEBIM,munResStatus,munResTipo,munResNome,munResUf
0,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-19,Masculino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
1,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-21,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
2,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-25,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
3,12 anos ou mais,37 a 41 semanas,Única,Cesáreo,2019-03-20,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia
4,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-03-23,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,12 anos ou mais,32 a 36 semanas,Única,Cesáreo,2019-12-13,Masculino,Branca,2020-09-28,NaN,3.2.01,2020-10-13,ATIVO,MUNIC,Vilhena,Rondônia
27024,8 a 11 anos,37 a 41 semanas,Única,Vaginal,2019-10-04,Masculino,Branca,2019-10-16,NaN,3.2.01,2019-10-21,ATIVO,MUNIC,Chupinguaia,Rondônia
27025,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-08-02,Masculino,Parda,2019-08-07,NaN,3.2.00,2019-08-07,ATIVO,MUNIC,Vilhena,Rondônia
27026,8 a 11 anos,32 a 36 semanas,Única,Vaginal,2019-12-23,Masculino,Parda,2020-01-07,NaN,3.2.00,2020-01-07,ATIVO,MUNIC,Vilhena,Rondônia
27027,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-12-27,Masculino,Parda,2020-10-15,NaN,3.2.01,2020-10-16,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia

In [18]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')